### ISSUE TITLE
There should be some option to enable GPG checks

### ISSUE THREAD

**Issue by kleini** [jarosser06/chef-zypper#3]
Using the resource yum_repository it is easy to enable GPG checks for installed packages:

```
    yum_repository reponame do
        description   "package repo for component #{reponame}"
        baseurl             url
        gpgkey           node['open-xchange']['repository']['buildkey']
        gpgcheck       node['open-xchange']['repository']['buildkey'].length > 0 ? true : false
        sslverify      node['open-xchange']['repository']['sslverify']
        action :create
    end
```

You just need to add the gpgcheck attribute. I don't see any according attribute for zypper and when installing packages I see the following warning all the time:

```
[2015-09-09T18:40:30+03:00] WARN: Chef::Config[:zypper_check_gpg] was not set. All packages will be installed without gpg signature checks. This is a security hazard
```

**Comment by jarosser06** [comment]
It looks like those warnings are caused by the zypper package resource. The only fix I can see is to set your Chef::Config[:zypper_check_gpg] to true. 

https://github.com/chef/chef/issues/2339

**Comment by kleini** [comment]
I use now that configuration for Chef for the zypper package resource and the warnings are gone.
